# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- manual

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/MyTelmyApp_$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS-test-connection'
    regionName: 'ap-south-1'
    bucketName: 'mytelmytestbucket'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    globExpressions: '**'
    targetFolder: 'MyTelmyAppDeliveries'
- task: CodeDeployDeployApplication@1
  inputs:
    awsCredentials: 'AWS-test-connection'
    regionName: 'ap-south-1'
    applicationName: 'Telmy'
    deploymentGroupName: 'Dev'
    deploymentRevisionSource: 's3'
    bucketName: 'mytelmytestbucket'
    bundleKey: 'MyTelmyAppDeliveries/MyTelmyApp_$(Build.BuildId).zip'
    description: 'Telmy Dev deployment'

- task: CodeDeployDeployApplication@1
  inputs:
    awsCredentials: 'AWS-test-connection'
    regionName: 'ap-south-1'
    applicationName: 'Telmy'
    deploymentGroupName: 'Staging'
    deploymentRevisionSource: 's3'
    bucketName: 'mytelmytestbucket'
    bundleKey: 'MyTelmyAppDeliveries/MyTelmyApp_$(Build.BuildId).zip'
    description: 'Telmy Staging deployment'

- task: CodeDeployDeployApplication@1
  inputs:
    awsCredentials: 'AWS-test-connection'
    regionName: 'ap-south-1'
    applicationName: 'Telmy'
    deploymentGroupName: 'Production'
    deploymentRevisionSource: 's3'
    bucketName: 'mytelmytestbucket'
    bundleKey: 'MyTelmyAppDeliveries/MyTelmyApp_$(Build.BuildId).zip'
    description: 'Telmy Production deployment'
